version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6
     steps:
       - checkout

       - run: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
       - run: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
       - run: sudo pip install -q awscli --upgrade
       
       - run: aws --version
       - run: ls
